export const catalogData = {
  Dev: {
    AppBlocks: {
      commonMicroservices: [],
      generators: [],
      workflows: [],
    },
    LibraryAndSDKs: {},
    BuildDeployTemplates: {},
    ISVSolutions: {},
    DataFlows: {},
  },
  Sec: {
    ComplianceRules: {},
    CompliancePolicies: {},
    ComplianceAuditors: {},
    CodeSecurityTemplates: {},
    ConainerSecurityTemplates: {},
    DataSecurityTemplates: {},
  },
  Ops: {
    CloudDashBoards: [
      {
        id: 1,
        name: 'AWS CloudTrail Overview',
        description:
          'Overview of your AWS users, resources, network and security events, top 10 users, failed logins, resource creation and deletion',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CLOUDTRAIL',
        jsonLocation: 's3://updated-dashboards-bucket/NewDashboards/CloudTrail/AWS CloudTrail - Overview.txt',
      },
      {
        id: 2,
        name: 'AWS CloudTrail - User Monitoring',
        description: 'AWS users, volumes attach and detach, instance launch and termination by users',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CLOUDTRAIL',
        jsonLocation: 's3://updated-dashboards-bucket/NewDashboards/CloudTrail/AWS CloudTrail - User Monitoring.txt',
      },
      {
        id: 3,
        name: 'AWS-CloudTrail-Network-And-Security',
        description: 'AWS CloudTrail Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CloudTrail-Network-Security',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/CloudTrail/AWS Cloudtrail Network & Security.json',
      },
      {
        id: 5,
        name: 'AWS-CloudTrail-Operations',
        description: 'AWS CloudTrail Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CloudTrail-Operations',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/CloudTrail/AWS CloudTrail - Operations.json',
      },
      {
        id: 6,
        name: 'AWS-CloudTrail-Console-Logins',
        description: 'AWS CloudTrail Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CloudTrail-Operations',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/CloudTrail/Console Logins.json',
      },
      {
        id: 8,
        name: 'AWS-Config-Overview',
        description: 'AWS CloudTrail Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Config-Operations',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/Config/AWS Config Overview.json',
      },
      {
        id: 10,
        name: 'AWS-ELB-Application-Overview',
        description: 'AWS ELB Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ELB-Application-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS ELB/ALB/AWS ELB Application Load Balancer Overview.json',
      },
      {
        id: 12,
        name: 'AWS-ELB-Status-Code-Analysis',
        description: 'AWS ELB Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ELB-Application-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS ELB/ALB/AWS ELB Application Status Code Analysis.json',
      },
      {
        id: 13,
        name: 'AWS-ELB-Request-Analysis',
        description: 'AWS ELB Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ELB-Application-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS ELB/ALB/AWS ELB - Application - Request Analysis.json',
      },
      {
        id: 43,
        name: 'AWS-LAMBDA-OVERVIEW',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'LAMBDA-Operations',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/AWS Lambda - Overview.json',
      },
      {
        id: 45,
        name: 'AWS-LAMBDA-CLOUDTRAIL-EVENT-OVERVIEW',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'LAMBDA-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/LAMBDA-CLOUDTRAIL-EVENTS-OVERVIEW.json',
      },
      {
        id: 46,
        name: 'AWS-LAMBDA-CLOUDWATCH-DURATIONS-AND-MEMORY',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'LAMBDA-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/Aws-lambda logs/Aws-lambda-cloudwatch-duration-memory.json',
      },
      {
        id: 47,
        name: 'AWS-LAMBDA-CLOUDWATCH-DURATIONS-AND-MEMORY',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'LAMBDA-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/AWS-LAMBDA-METRICS/aws lambda cloudwatch durations metric.json',
      },
      {
        id: 48,
        name: 'AWS-LAMBDA-CLOUDWATCH-USAGE',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'LAMBDA-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/Aws Lambda - Cloudwatch - usage.json',
      },
      {
        id: 49,
        name: 'AWS-LAMBDA-ULM-OVERVIEW',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'LAMBDA-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/Aws-lambda logs/lambda ulm overview.json',
      },
      {
        id: 50,
        name: 'AWS-LAMBDA-ULM-OVERVIEW',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: ' METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'LAMBDA-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/AWS-LAMBDA-METRICS/lambda ulm overview metrics.json',
      },
      {
        id: 51,
        name: 'AWS-LAMBDA-ULM-ERROR-ANALYSIS',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'LAMBDA-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/AWS-LAMBDA-METRICS/lambda ulm error analysis metrics.json',
      },
      {
        id: 52,
        name: 'AWS-LAMBDA-ULM-ERROR-ANALYSIS',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'LAMBDA-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/Aws-lambda logs/lambda ulm error analysis logs.json',
      },
      {
        id: 53,
        name: 'AWS-LAMBDA-ULM-PERFORMANCE-ANALYSIS',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'LAMBDA-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/Aws-lambda logs/lambda ulm Performance analysis logs.json',
      },
      {
        id: 54,
        name: 'AWS-LAMBDA-ULM-PERFORMANCE-ANALYSIS',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'LAMBDA-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/AWS-LAMBDA-METRICS/lambda ulm Performance analysis metrics.json',
      },
      {
        id: 57,
        name: 'AWS-LAMBDA-ULM-REQUEST-ANALYSIS',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'LAMBDA-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/AWS Lambda ULM Request Analysis.json',
      },
      {
        id: 61,
        name: 'AWS-LAMBDA-ULM-USAGE-ANALYSIS',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'LAMBDA-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/Amazon Lambda ulm usage analysis.json',
      },
      {
        id: 62,
        name: 'AWS-SECURITY-HUB-OVERVIEW',
        description: 'AWS SECURITY Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SECURITY-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon Security Hub/AWS Security Hub -  Overview.json',
      },
      {
        id: 66,
        name: 'AWS-SECURITY-HUB-COMPLIANCE-RESOURCE-EFFECTED',
        description: 'AWS SECURITY Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SECURITY-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon Security Hub/Amazon Security hub resource effected.json',
      },
      {
        id: 69,
        name: 'AWS-WAF-OVERVIEW',
        description: 'AWS WAF Operations',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'WAF-Operations',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS WAF/waf overview metrics.json',
      },
      {
        id: 69,
        name: 'AWS-WAF-OVERVIEW',
        description: 'AWS WAF Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'WAF-Operations',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS WAF/waf overview logs.json',
      },
      {
        id: 71,
        name: 'AWS-WAF-TRAFFIC',
        description: 'AWS WAF Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'WAF-Operations',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS WAF/AWS WAF- Traffic.json',
      },
      {
        id: 76,
        name: 'AWS-DYNAMODB-CAPACITY-PLANNING',
        description: 'AWS DYNAMODB Operations',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'DYNAMODB-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS DynamoDb/Amazon DynamoDB - Capacity Planning.json',
      },
      {
        id: 78,
        name: 'AWS-DYNAMODB-EVENTS',
        description: 'AWS DYNAMODB Event Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'DYNAMODB-Operations',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS DynamoDb/Amazon DynamoDB - Events.json',
      },
      {
        id: 80,
        name: 'AWS-DYNAMODB-LATENCY-&-ERRORS',
        description: 'AWS DYNAMODB Latency and Errors Operations',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'DYNAMODB-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS DynamoDb/Amazon DynamoDB - Latency & Errors.json',
      },
      {
        id: 81,
        name: 'AWS-DYNAMODB-CAPACITY-PLANNING',
        description: 'AWS DYNAMODB Operations',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'DYNAMODB-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS DynamoDb/Amazon DynamoDB - Capacity Planning.json',
      },
      {
        id: 84,
        name: 'AWS-ECS-CPU-UTILIZATION-CLUSTER-&-SERVICE',
        description: 'AWS ECS Operations',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ECS-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ECS/AWS ECS Metrics/AWS ECS - CPU Utilization - Cluster & Service.json',
      },
      {
        id: 85,
        name: 'AWS-ECS-CPU-&-MEMORY-RESERVATION-CLUSTER',
        description: 'AWS ECS Operations',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ECS-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ECS/AWS ECS Metrics/AWS ECS - CPU & Memory Reservation - Cluster.json',
      },
      {
        id: 86,
        name: 'AWS-ECS-EVENTS',
        description: 'AWS ECS Events',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ECS-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ECS/AWS ECS Logs/Amazon ECS - Events.json',
      },
      {
        id: 87,
        name: 'Amazon-ECS-Memory-Utilization–Cluster-&-Service',
        description: 'AWS ECS Memory-Cluster-Service Operations',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'Metric',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ECS-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ECS/AWS ECS Metrics/AWS ECS - Memory Utilization - Cluster and Service.json',
      },
      {
        id: 93,
        name: 'Amazon-ElastiCache-REDIS-ULM-EVENT-OVERVIEW',
        description: 'AWS ELASTICACHE Events Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ElastiCache-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ElastiCache Redis/Amazon-Elasticache-redis-ulm-events-overview.json',
      },
      {
        id: 97,
        name: 'Amazon-ElastiCache-Redis-ULM-Performance-Overview',
        description: 'AWS ElastiCache Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ElastiCache-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ElastiCache Redis/Amazon ElastiCache Redis ULM-Performance Overview.json',
      },
      {
        id: 98,
        name: 'Amazon ElastiCache Redis ULM-Performance Overview',
        description: 'AWS ElastiCache Redis ULM Monitoring Performance Overview',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ElastiCache Redis',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ElastiCache Redis/Amazon ElastiCache Redis ULM-Performance Overview.json',
      },
      {
        id: 99,
        name: 'Amazon ElastiCache Redis ULM–Performance by Cluster',
        description: 'AWS ElastiCache Redis ULM Performance Monitoring by Cluster',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ElastiCache Redis',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ElastiCache Redis/Amazon ElastiCache Redis ULM-Performance by Cluster.json',
      },
      {
        id: 101,
        name: 'Amazon ElastiCache Redis ULM–Performance by Host',
        description: 'AWS ElastiCache Redis ULM Monitoring Performance by Host',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ElastiCache Redis',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ElastiCache Redis/Amazon ElastiCache Redis ULM-Performance by Host.json',
      },
      {
        id: 104,
        name: 'Amazon ElastiCache Redis ULM – Notifications',
        description: 'AWS ElastiCache Redis ULM Monitoring Notifications',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ElastiCache Redis',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ElastiCache Redis/Amazon-elasticache-redis-ulm-notifications.json',
      },
      {
        id: 105,
        name: 'Amazon GuardDuty - Overview',
        description: 'Amazon GuardDuty Monitoring Performance Overview',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'GuardDuty',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon GuardDuty/Amazon GuardDuty-Overview.json',
      },
      {
        id: 106,
        name: 'Amazon GuardDuty – CloudTrail Details',
        description: 'Amazon GuardDuty Monitoring CloudTrail Details',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'GuardDuty',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon GuardDuty/Amazon GuardDuty-CloudTrail-Details.json',
      },
      {
        id: 108,
        name: 'Amazon GuardDuty - Details(VPC,Subnet,Security Group)',
        description: 'Amazon GuardDuty Monitoring VPC,Subnet,Security Group Details',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'GuardDuty',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon GuardDuty/Amazon GuardDuty-Details(VPC,SUBNETS.SG).json',
      },
      {
        id: 111,
        name: 'Amazon Kinesis – Streams - Events',
        description: 'Amazon Kinesis Streams Monitoring Events',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Kinesis',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS kinesis/Amazon Kinesis - Streams - Events.json',
      },
      {
        id: 118,
        name: 'Amazon Redshift - Overview',
        description: 'Amazon Redshift Monitoring Performance Overview ',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Redshift',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Redshift/AWS - RedShift Overview.json',
      },
      {
        id: 119,
        name: 'Amazon Redshift - Overview',
        description: 'Amazon Redshift Monitoring Performance Overview ',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Redshift',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Redshift/AWS - RedShift Overview.json',
      },
      {
        id: 120,
        name: 'Amazon Redshift – Audit - Connection Log',
        description: 'Amazon Redshift Monitoring and Audit connection Log',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'AVAILABILITY',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Redshift',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Redshift/AWS - Redshift - Audit - Connection Log.json',
      },
      {
        id: 125,
        name: 'Amazon Redshift – CloudTrail Events Overview',
        description: 'Amazon Redshift Monitoring and Overview of CloudTrail Events',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'AVAILABILITY',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Redshift',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Redshift/AWS - RedShift - CloudTrail events Overview1.json',
      },
      {
        id: 127,
        name: 'Amazon Redshift – Resource Utilization by ClusterIdentifier',
        description: 'Amazon Redshift Monitoring Resource Utilization by ClusterIdentifier ',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Redshift',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Redshift/AWS-Redshift-Resource utilization by cluster identifier.json',
      },
      {
        id: 128,
        name: 'Amazon Redshift – Resource Utilization by NodeID',
        description: 'Amazon Redshift Monitoring Resource Utilization by NodeID ',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Redshift',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Redshift/AWS-Redshift-Resource utilization by NODE ID.json',
      },
      {
        id: 132,
        name: 'Amazon SES – CloudTrail Events Overview',
        description: 'Amazon SES Monitoring and Overview of CloudTrail Events',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SES',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon SES/Amazon SES - Cloud Trail Events Overview.json',
      },
      {
        id: 134,
        name: 'Amazon SES –CloudTrail Events by Event Name',
        description: 'Amazon SES Monitoring of CloudTrail Events by Event name',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SES',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon SES/AWS-SES-CLOUDTRAIL-EVENTS-BY-EVENTNAMES.json',
      },
      {
        id: 141,
        name: 'Amazon SNS - Overview',
        description: 'Amazon SNS Performance Monitoring and OverView',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SNS',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS SNS/sns overview metrics.json',
      },
      {
        id: 142,
        name: 'Amazon SNS - Overview',
        description: 'Amazon SNS Performance Monitoring and OverView',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SNS',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS SNS/sns overview logs.json',
      },
      {
        id: 143,
        name: 'Amazon SNS–Metric by Application & Platform',
        description: 'Amazon SNS Application & Platform Monitoring by metrics',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SNS',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS SNS/Amazon SNS - Metric By Application And Platform.json',
      },
      {
        id: 145,
        name: 'Amazon SNS – Metric by Region',
        description: 'Amazon SNS Region Monitoring by metrics',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SNS',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS SNS/Amazon SNS - Metric By Region.json',
      },
      {
        id: 146,
        name: 'Amazon SNS – Metric by TopicName',
        description: 'Amazon SNS TopicName Monitoring by metrics',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SNS',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS SNS/Amazon SNS - Metric By TopicName.json',
      },
      {
        id: 147,
        name: 'Amazon SNS – CloudTrail Events',
        description: 'Amazon SNS Monitoring by CloudTrail Events',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SNS',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS SNS/Amazon SNS - CloudTrail Events.json',
      },
      {
        id: 149,
        name: 'Amazon SNS – CloudTrail Events',
        description: 'Amazon SQS Monitoring  by CloudTrail Events',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SQS',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS-SQS/AWS-SQS-CloudTrail-Events.json',
      },
      {
        id: 151,
        name: 'Amazon SQS – Overview',
        description: 'Amazon SQS Monitoring and Overview',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SQS',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS-SQS/sqs overview logs.json',
      },
      {
        id: 152,
        name: 'Amazon SQS – Overview',
        description: 'Amazon SQS Monitoring and Overview',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SQS',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS-SQS/sqs overview metrics.json',
      },
      {
        id: 153,
        name: 'Amazon SQS by QueueName',
        description: 'Amazon SQS Monitoring by QueueName',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SQS',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS-SQS/AWS-SQS-QueueName.json',
      },
      {
        id: 155,
        name: 'Amazon SQS by Region',
        description: 'Amazon SQS Monitoring by Region',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SQS',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS-SQS/AWS-SQS-By-Region.json',
      },
      {
        id: 157,
        name: 'Amazon VPC Flow Logs - Overview',
        description: 'Amazon VPC Flow Logs Monitoring and OverView',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'VPC',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/vpc/Amazon VPC Flow Logs - Overview.json',
      },
      {
        id: 159,
        name: 'Amazon VPC Flow Logs - Traffic',
        description: 'Amazon VPC Flow Logs Monitoring Traffic',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'VPC',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/vpc/Amazon VPC Flow Logs - Traffic.json',
      },
      {
        id: 161,
        name: 'Amazon VPC Flow Logs - Accepts',
        description: 'Amazon VPC Flow Logs Monitoring by Accepts',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'VPC',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/vpc/Amazon VPC Flow Logs - Accepts.json',
      },
      {
        id: 163,
        name: 'Amazon VPC Flow Logs - Rejects',
        description: 'Amazon VPC Flow Logs Monitoring by Rejects',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'VPC',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/vpc/Amazon VPC Flow Logs - Rejects.json',
      },
      {
        id: 167,
        name: 'CIS AWS Monitoring – Access & Authentication',
        description: 'CIS AWS Monitoring Access & Authentication',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CIS',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/CIS AWS Monitoring- Access & Authentication/CIS AWS Monitoring – Access & Authentication.json',
      },
      {
        id: 168,
        name: 'CIS AWS Monitoring – Change Control',
        description: 'CIS AWS Monitoring Change Control',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CIS',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/CIS AWS Monitoring- Access & Authentication/CIS AWS Monitoring - Change Control.json',
      },
      {
        id: 169,
        name: 'GI GuardDuty – Global Baseline',
        description: 'GI GuardDuty Monitoring Global Baseline',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'GI GuardDuty',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon GI GuardDuty/GI GuardDuty Global Baseline.json',
      },
      {
        id: 173,
        name: 'GI GuardDuty – Findings Analysis',
        description: 'GI GuardDuty Monitoring and Findings Analysis',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'GI GuardDuty',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon GI GuardDuty/GI GuardDuty Finding Analysis.json',
      },
      {
        id: 173.1,
        name: 'GI GuardDuty – Findings Analysis(1)',
        description: 'GI GuardDuty Monitoring and Findings Analysis',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'GI GuardDuty',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon GI GuardDuty/GI GuardDuty Finding Analysis(1).json',
      },
      {
        id: 180,
        name: 'GI CloudTrail – Tactics & Techniques',
        description: 'GI CloudTrail Monitoring Tactics & Techniques',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'GI CloudTrail',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon GI CloudTrail/GI CloudTrail Tactic and Techniques.json',
      },
      {
        id: 184,
        name: 'GI CloudTrail – Action Plan',
        description: 'GI CloudTrail Monitoring by Action Plan',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'GI CloudTrail',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon GI CloudTrail/GI CloudTrail Action Plan.json',
      },
      {
        id: 185,
        name: 'GI CloudTrail – Action Plan(1)',
        description: 'GI CloudTrail Monitoring by Action Plan',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'GI CloudTrail',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon GI CloudTrail/GI CloudTrail Action Plan(1).json',
      },
      {
        id: 187,
        name: 'AWS CloudTrail - Access Monitoring',
        description: 'CloudTrail - Access Monitoring Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CloudTrail',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/CloudTrail/AWS-CloudTrails-logs/AWS CloudTrail - Access Monitoring.json',
      },
      {
        id: 188,
        name: 'AWS CloudTrail - Account, System Monitoring',
        description: 'CloudTrail - Account & System Monitoring Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CloudTrail',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/CloudTrail/AWS-CloudTrails-logs/AWS CloudTrail - Account , System Monitoring.json',
      },
      {
        id: 188,
        name: 'AWS CloudTrail -Privileged Activity',
        description: 'CloudTrail -Privileged Activity Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CloudTrail',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/CloudTrail/AWS-CloudTrails-logs/AWS CloudTrail -Privileged Activity.json',
      },
      {
        id: 189,
        name: 'AWS CloudTrail -Login Activity',
        description: 'CloudTrail -Login Activity Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CloudTrail',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/CloudTrail/AWS-CloudTrails-logs/AWS CloudTrail -Login Activity.json',
      },
      {
        id: 197,
        name: 'AWS WAF - Security Analytics Traffic',
        description: 'WAF - Security Analytics Traffic Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'WAF',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS WAF/waf-security-analysis-traffic.json',
      },
      {
        id: 199,
        name: 'AWS WAF - Security Monitoring Overview',
        description: 'WAF - Security Monitoring Overview Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'WAF',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS WAF/waf-security-monitoring.json',
      },
      {
        id: 1,
        name: 'Azure Active Directory - Overview',
        description: 'Azure Active Directory Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Active Directory-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Active Directory/Azure Active Directory - Overview.json',
      },
      {
        id: 2,
        name: 'Azure Active Directory - Application Management',
        description: 'Azure Active Directory Applicaion Management Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Active Directory-Application Management Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Active Directory/Azure Active Directory - Application Management.json',
      },
      {
        id: 3,
        name: 'Azure Active Directory -  Authorization/Authentication',
        description: 'Azure Active Directory Applicaion Management Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Active Directory-Application Management Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Active Directory/Azure Active Directory - Authorization, Authentication.json',
      },
      {
        id: 4,
        name: 'Azure Active Directiory - Directory Management',
        description: 'Azure Active Directory management Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Active Directory Management Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Active Directory/Azure Active Directory - Directory Management.json',
      },
      {
        id: 5,
        name: 'Azure Active Directory - Failure Sign-in Events ',
        description: 'Azure Active Directory Failed Sign-in Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Active Directory Failed Sign-in Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Active Directory/Azure Active Directory -- Failure Sign_In Events.json',
      },
      {
        id: 6,
        name: 'Azure Active Directory - Successful  Sign-in Events ',
        description: 'Azure Active Directory Success Sign-in Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Active Directory Success Sign-in Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Active Directory/Azure Active Directory - Success Sign-Ins.json',
      },
      {
        id: 7,
        name: 'Azure Audit - Overview',
        description: 'Azure Audit - Overview- Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Azure Audit - Overview',
        jsonLocation: 's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Audit/Azure Audit - OverView.json',
      },
      {
        id: 8,
        name: 'Azure Audit Resource usage',
        description: 'Azure Audit Resource usage - Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Azure Audit - Resource Usasge',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Audit/Azure Audit - Resource Usage.json',
      },
      {
        id: 9,
        name: 'Azure SQL – Blocking Stats',
        description: ' SQL – Blocking Stats - Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Azure SQL – Blocking Stats',
        jsonLocation: 's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure SQL/Azure SQL-Blocking Stats.json',
      },
      {
        id: 10,
        name: 'Azure SQL –Errors',
        description: ' SQL – Errors - Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Azure SQL – Errors',
        jsonLocation: 's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure SQL/Azure SQL Errors.json',
      },
      {
        id: 11,
        name: 'Azure SQL – QueryStoreRuntime Stats',
        description: 'SQL – QueryStoreRuntime Stats  Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Azure SQL – QueryStoreRuntime Stats',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure SQL/Azure SQL - Query StoreRuntime Stats.json',
      },
      {
        id: 12,
        name: 'Azure SQL – QueryStoreWait Stats',
        description: 'Azure SQL – QueryStoreWait Stats  Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Azure SQL – QueryStoreRuntime',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure SQL/Azure SQL-Query Store Wait Stats.json',
      },
      {
        id: 13,
        name: 'Azure SQL – Timeouts',
        description: 'Azure SQL – Timeouts  Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Azure SQL – Timeouts',
        jsonLocation: 's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure SQL/Azure SQL TimeOuts.json',
      },
      {
        id: 14,
        name: 'Azure Web Apps Overview',
        description: 'Azure Web Apps – Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Azure Web Apps',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Web Apps/Azure Web Apps-Overview.json',
      },
      {
        id: 15,
        name: 'Azure Web Apps – Server Operation – Errors and Response Codes',
        description: 'Azure Web Server Operation – Errors and Response Codes',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Azure Web Apps',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Web Apps/Azure Web Apps-Server Operation-Errors and Response Codes.json',
      },
      {
        id: 16,
        name: 'Azure Web Apps – Traffic Insights – Apps and Requests',
        description: 'Azure Web Apps – Traffic Insights – Apps and Requests',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Azure Web Apps',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Web Apps/Azure Web Apps - Traffic insights - Apps and requests.json',
      },
      {
        id: 17,
        name: 'Office 365 – SharePoint – Shared Content Non-Domain Activities',
        description: 'Office 365 – SharePoint – Shared Content Non-Domain Activities Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Office 365',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Office 365/Office 365 – SharePoint – Shared Content Non – Domain Activities.json',
      },
    ],
    DataSources: [
      {
        id: 1,
        name: 'AWS-PullMetric-Api',
        description: 'Pull AWS metrics with Cloud API',
        Type: 'PullApi',
        DataType: 'METRIC',
        associatedWorkflowTemplate: 's3://...',
        associatedCloud: 'AWS',
        associatedCreds: 'Vault',
        associatedApplicationLocation: 'AppKubeMain',
        associatedTargetDs: 'NA',
      },
      {
        id: 2,
        name: 'AWS-PullLogs-Api',
        description: 'Pull AWS Logs with Cloud API',
        Type: 'PullApi',
        DataType: 'LOG',
        associatedWorkflowTemplate: 's3://...',
        associatedCloud: 'AWS',
        associatedCreds: 'Vault',
        associatedApplicationLocation: 'AppKubeMain',
        associatedTargetDs: 'NA',
      },
      {
        id: 3,
        name: 'AWS-PullLogs-Local',
        description: 'Receive AWS Logs and Store in Local ES',
        Type: 'ReceiveAndStoreLogs',
        DataType: 'LOG',
        associatedWorkflowTemplate: 's3://...',
        associatedCloud: 'AWS',
        associatedCreds: 'Vault',
        associatedApplicationLocation: 'LogManager',
        associatedTargetDsType: 'ES',
      },
      {
        id: 4,
        name: 'AWS-StoreTrace-Local',
        description: 'Receive Traces and Store in Local Zipkin DB',
        Type: 'ReceiveAndStoreTrace',
        DataType: 'Trace',
        associatedWorkflowTemplate: 's3://...',
        associatedCloud: 'AWS',
        associatedCreds: 'Vault',
        associatedApplicationLocation: 'TraceManager',
        associatedTargetDsType: 'Zipkin',
      },
      {
        id: 4,
        name: 'Azure-PullMetric-Api',
        description: 'Pull Azure metrics with Cloud API',
        Type: 'PullApi',
        DataType: 'METRIC',
        associatedWorkflowTemplate: 's3://...',
        associatedCloud: 'Azure',
        associatedCreds: 'Vault',
        associatedApplicationLocation: 'AppKubeMain',
        associatedTargetDs: 'NA',
      },
      {
        id: 5,
        name: 'Azure-PullLogs-Api',
        description: 'Pull Azure Logs with Cloud API',
        Type: 'PullApi',
        DataType: 'LOG',
        associatedWorkflowTemplate: 's3://...',
        associatedCloud: 'Azure',
        associatedCreds: 'Vault',
        associatedApplicationLocation: 'AppKubeMain',
        associatedTargetDs: 'NA',
      },
      {
        id: 6,
        name: 'Azure-PullLogs-Local',
        description: 'Receive Azure Logs and Store in Local ES',
        Type: 'ReceiveAndStoreLogs',
        DataType: 'LOG',
        associatedWorkflowTemplate: 's3://...',
        associatedCloud: 'Azure',
        associatedCreds: 'Vault',
        associatedApplicationLocation: 'LogManager',
        associatedTargetDsType: 'ES',
      },
      {
        id: 7,
        name: 'Azure-StoreTrace-Local',
        description: 'Receive Traces and Store in Local Zipkin DB',
        Type: 'ReceiveAndStoreTrace',
        DataType: 'Trace',
        associatedWorkflowTemplate: 's3://...',
        associatedCloud: 'AWS',
        associatedCreds: 'Vault',
        associatedApplicationLocation: 'TraceManager',
        associatedTargetDsType: 'Zipkin',
      },
      {
        id: 1,
        name: 'Azure Active Directory - Overview',
        description: 'Azure Active Directory Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Active Directory-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Active Directory/Azure Active Directory - Overview.json',
      },
    ],
    ProvisioningTemplates: [
      {
        id: 1,
        name: 'AWS-Landing-Zone',
        description: 'Create AWS Accounts with Best Practices',
        Type: 'LandingZone',
        actOn: 'MainProduct',
        associatedSpecsTemplate: 's3://...',
        associatedCloud: 'AWS',
        associatedCreds: 'Vault',
      },
      {
        id: 2,
        name: 'Azure-Landing-Zone',
        description: 'Create Azure Account and Subscription with Best Practices',
        Type: 'LandingZone',
        actOn: 'MainProduct',
        associatedSpecsTemplate: 's3://...',
        associatedCloud: 'Azure',
        associatedCreds: 'Vault',
      },
      {
        id: 3,
        name: 'Google-Landing-Zone',
        description: 'Create Google Project with Best Practices',
        Type: 'LandingZone',
        actOn: 'MainProduct',
        associatedSpecsTemplate: 's3://...',
        associatedCloud: 'Google',
        associatedCreds: 'Vault',
      },
      {
        id: 4,
        name: 'AWS-Product-Enclave',
        description: 'Create AWS VPC/Gateway/Firewall Services',
        Type: 'ProductEnclave',
        actOn: 'LandingZone',
        associatedSpecsTemplate: 's3://...',
        associatedCloud: 'AWS',
        associatedCreds: 'Vault',
      },
      {
        id: 5,
        name: 'Azure-Product-Enclave',
        description: 'Create Azure VPC/Gateway/Firewall Services',
        Type: 'ProductEnclave',
        actOn: 'LandingZone',
        associatedSpecsTemplate: 's3://...',
        associatedCloud: 'Azure',
        associatedCreds: 'Vault',
      },
      {
        id: 6,
        name: 'Google-Product-Enclave',
        description: 'Create Google VPC/Gateway/Firewall Services',
        Type: 'ProductEnclave',
        actOn: 'LandingZone',
        associatedSpecsTemplate: 's3://...',
        associatedCloud: 'Google',
        associatedCreds: 'Vault',
      },
      {
        id: 7,
        name: 'AWS-Product-Cluster',
        description: 'Create EKS k8 cluster with best practices',
        Type: 'ProductCluster',
        actOn: 'ProductEnclave',
        associatedSpecsTemplate: 's3://...',
        associatedCloud: 'AWS',
        associatedCreds: 'Vault',
      },
      {
        id: 8,
        name: 'Azure-Product-Cluster',
        description: 'Create Azure AKS k8 cluster with best practices',
        Type: 'ProductCluster',
        actOn: 'ProductEnclave',
        associatedSpecsTemplate: 's3://...',
        associatedCloud: 'Azure',
        associatedCreds: 'Vault',
      },
      {
        id: 9,
        name: 'Google-Product-Cluster',
        description: 'Create Google k8 cluster with best practices',
        Type: 'ProductCluster',
        actOn: 'ProductEnclave',
        associatedSpecsTemplate: 's3://...',
        associatedCloud: 'Google',
        associatedCreds: 'Vault',
      },
      {
        id: 10,
        name: 'Common-Service-File-Repo',
        description: 'Provision Filerepo Common Services',
        Type: 'CommonService',
        actOn: 'ProductEnclave',
        associatedSpecsTemplate: 's3://...',
        associatedCloud: 'Google',
        associatedCreds: 'Vault',
      },
    ],
    AlertRules: {},
    Workflows: {},
    Collectors: {},
    Diagonostics: {},
    kubeOperators: {},
  },
};
