export const catalogData = {
  dev: {
    appBlocks: {
      commonMicroservices: [],
      generators: [],
      workflows: [],
    },
    libraryAndSDKs: {
      name: null,
    },
    buildDeployTemplates: {
      name: null,
    },
    dataFlows: {
      name: null,
    },
    isvsolutions: null,
  },
  sec: {
    complianceRules: {
      name: null,
    },
    compliancePolicies: {
      name: null,
    },
    complianceAuditors: {
      name: null,
    },
    codeSecurityTemplates: {
      name: null,
    },
    conainerSecurityTemplates: {
      name: null,
    },
    dataSecurityTemplates: {
      name: null,
    },
  },
  ops: {
    cloudDashBoards: [
      {
        id: 1,
        name: 'AWS CloudTrail Overview',
        description:
          'Overview of your AWS users, resources, network and security events, top 10 users, failed logins, resource creation and deletion',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CLOUDTRAIL',
        jsonLocation: 's3://updated-dashboards-bucket/NewDashboards/CloudTrail/AWS CloudTrail - Overview.txt',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/CloudTrail/Overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/CloudTrail/Overview1.png',
        ],
      },
      {
        id: 2,
        name: 'AWS CloudTrail - User Monitoring',
        description: 'AWS users, volumes attach and detach, instance launch and termination by users',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CLOUDTRAIL',
        jsonLocation: 's3://updated-dashboards-bucket/NewDashboards/CloudTrail/AWS CloudTrail - User Monitoring.txt',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/CloudTrail/User-Monitoring.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/CloudTrail/User-Monitoring1.png',
        ],
      },
      {
        id: 3,
        name: 'AWS-CloudTrail-Network-And-Security',
        description: 'AWS CloudTrail Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'Availability',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CloudTrail-Network-Security',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/CloudTrail/AWS Cloudtrail Network & Security.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/CloudTrail/Network-and-security1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/CloudTrail/Network-and-security2.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/CloudTrail/Network-and-security3.png',
        ],
      },
      {
        id: 5,
        name: 'AWS-CloudTrail-Operations',
        description: 'AWS CloudTrail Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'Availability',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CloudTrail',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/CloudTrail/AWS CloudTrail - Operations.json',
        images: ['https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/CloudTrail/AWS-CLOUDTRAILOPERATIONS1.png'],
      },
      {
        id: 6,
        name: 'AWS-CloudTrail-Console-Logins',
        description: 'AWS CloudTrail Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'Reliability',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CloudTrail',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/CloudTrail/Console Logins.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/CloudTrail/AWS-CLOUDTRAIL-CONSOLE-LOGINS1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/CloudTrail/AWS-CLOUDTRAIL-CONSOLE-LOGINS2.png',
        ],
      },
      {
        id: 8,
        name: 'AWS-Config-Overview',
        description: 'AWS Config Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'Availability',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Config',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/Config/AWS Config Overview.json',
        images: ['https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Config/Overview.png'],
      },
      {
        id: 10,
        name: 'AWS-ELB-Application-Overview',
        description: 'AWS ELB Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ELB',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS ELB/ALB/AWS ELB Application Load Balancer Overview.json',
        images: ['https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ELB/Application-Overview.png'],
      },
      {
        id: 12,
        name: 'AWS-ELB-Status-Code-Analysis',
        description: 'AWS ELB Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ELB',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS ELB/ALB/AWS ELB Application Status Code Analysis.json',
        images: ['https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ELB/STATUS-CODE-ANALYSIS.png'],
      },
      {
        id: 13,
        name: 'AWS-ELB-Request-Analysis',
        description: 'AWS ELB Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'RELIABILITY',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ELB',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS ELB/ALB/AWS ELB - Application - Request Analysis.json',
        images: ['https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ELB/Request-Analysis.png'],
      },
      {
        id: 43,
        name: 'AWS-LAMBDA-OVERVIEW',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'RELIABILITY',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Lambda',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/AWS Lambda - Overview.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-Overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-Overview1.png',
        ],
      },
      {
        id: 45,
        name: 'AWS-LAMBDA-CLOUDTRAIL-EVENT-OVERVIEW',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'END USER STATS',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Lambda',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/LAMBDA-CLOUDTRAIL-EVENTS-OVERVIEW.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/CloudTrail-Events-Overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/CloudTrail-Events-Overview1.png',
        ],
      },
      {
        id: 46,
        name: 'AWS-LAMBDA-Cloudwatch-Duration-And-Memory',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'RELIABILITY',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Lambda',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/Aws-lambda logs/Aws-lambda-cloudwatch-duration-memory.json',
        images: ['https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/CloudWatch-Duration-And-Memory.png'],
      },
      {
        id: 47,
        name: 'AWS-LAMBDA-Cloudwatch-Duration-And-Memory',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'RELIABILITY',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Lambda',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/AWS-LAMBDA-METRICS/aws lambda cloudwatch durations metric.json',
        images: ['https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/CloudWatch-Duration-And-Memory.png'],
      },
      {
        id: 48,
        name: 'AWS-LAMBDA-Cloudwatch-Usage',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'LAMBDA-OperationsLambda',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/Aws Lambda - Cloudwatch - usage.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/CloudWatch-Usage.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/CloudWatch-Usage1.png',
        ],
      },
      {
        id: 49,
        name: 'AWS-LAMBDA-ULM-Overview',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Lambda',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/Aws-lambda logs/lambda ulm overview.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-ULM-Overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-ULM-Overview1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-ULM-Overview2.png',
        ],
      },
      {
        id: 50,
        name: 'AWS-LAMBDA-ULM-Overview',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: ' METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Lambda',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/AWS-LAMBDA-METRICS/lambda ulm overview metrics.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-ULM-Overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-ULM-Overview1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-ULM-Overview2.png',
        ],
      },
      {
        id: 51,
        name: 'AWS-LAMBDA-ULM-Error-Analysis',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Lambda',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/AWS-LAMBDA-METRICS/lambda ulm error analysis metrics.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-ULM-Error-Analysis.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-ULM-Error-Analysis1.png',
        ],
      },
      {
        id: 52,
        name: 'AWS-LAMBDA-ULM-Error-Aanlysis',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Lambda',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/Aws-lambda logs/lambda ulm error analysis logs.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-ULM-Error-Analysis.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-ULM-Error-Analysis1.png',
        ],
      },
      {
        id: 53,
        name: 'AWS-LAMBDA-ULM-Performance-Analysis',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Lambda',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/Aws-lambda logs/lambda ulm Performance analysis logs.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-ULM-Performance-Analysis.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-ULM-Performance-Analysis1.png',
        ],
      },
      {
        id: 54,
        name: 'AWS-LAMBDA-ULM-Performance-Analysis',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Lambda',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/AWS-LAMBDA-METRICS/lambda ulm Performance analysis metrics.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-ULM-Performance-Analysis.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-ULM-Performance-Analysis1.png',
        ],
      },
      {
        id: 57,
        name: 'AWS-LAMBDA-ULM-Request-Analysis',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Lambda',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/AWS Lambda ULM Request Analysis.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-ULM-Request-Analysis.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-ULM-Request-Analysis1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-ULM-Request-Analysis2.png',
        ],
      },
      {
        id: 61,
        name: 'AWS-LAMBDA-ULM-Usage-Analysis',
        description: 'AWS LAMBDA Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'RELIABILITY',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Lambda',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Lambda/Amazon Lambda ulm usage analysis.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-ULM-Usage-Analysis.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Lambda/Lambda-ULM-Usage-Analysis1.png',
        ],
      },
      {
        id: 62,
        name: 'AWS-Secutity-Hub-Overview',
        description: 'AWS SECURITY Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'RELIABILITY',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Security-hub',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon Security Hub/AWS Security Hub -  Overview.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Security-Hub/AWS- Security-Hub-Overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Security-Hub/AWS-Security Hub-Overview1.png',
        ],
      },
      {
        id: 66,
        name: 'AWS-Secutity-Hub-Resource-Effected',
        description: 'AWS SECURITY Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'RELIABILITY',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Security-hub',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon Security Hub/Amazon Security hub resource effected.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Security-Hub/AWS-Security-Hub -Resource-Effected.png',
        ],
      },
      {
        id: 71,
        name: 'AWS-WAF-TRAFFIC',
        description: 'AWS WAF Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'WAF-Operations',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS WAF/AWS WAF- Traffic.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/WAF/Security-Analysis-Traffic.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/WAF/Security-Analysis-Traffic1.png',
        ],
      },
      {
        id: 76,
        name: 'AWS-DYNAMODB-CAPACITY-PLANNING',
        description: 'AWS DYNAMODB Operations',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'DynamoDB',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS DynamoDb/Amazon DynamoDB - Capacity Planning.json',
        images: ['https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/DynamoDB/DynamoDB-CapacityPlanning.png'],
      },
      {
        id: 78,
        name: 'AWS-DYNAMODB-EVENTS',
        description: 'AWS DYNAMODB Event Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'DynamoDB',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS DynamoDb/Amazon DynamoDB - Events.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/DynamoDB/DynamoDB-Events.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/DynamoDB/DynamoDB-Events1.png',
        ],
      },
      {
        id: 80,
        name: 'AWS-DYNAMODB-LATENCY-&-ERRORS',
        description: 'AWS DYNAMODB Latency and Errors Operations',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'DynamoDB',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS DynamoDb/Amazon DynamoDB - Latency & Errors.json',
        images: ['https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/DynamoDB/Latency-And-Errors.png'],
      },
      {
        id: 81,
        name: 'AWS-DYNAMODB-CAPACITY-PLANNING',
        description: 'AWS DYNAMODB Operations',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'DynamoDB',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS DynamoDb/Amazon DynamoDB - Capacity Planning.json',
        images: ['https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/DynamoDB/DynamoDB-CapacityPlanning.png'],
      },
      {
        id: 82,
        name: 'AWS-ECS-Overview',
        description: 'AWS ECS Monitoring Overview',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ECS',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ECS/AWS ECS Metrics/AWS ECS Overview metrics.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ECS/Overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ECS/Overview1.png',
        ],
      },
      {
        id: 83,
        name: 'AWS-ECS-Overview',
        description: 'AWS ECS Monitoring Overview',
        associatedDataSourceType: 'AWS-PullLg-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ECS',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ECS/AWS ECS Logs/Amazon ECS - Events.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ECS/Overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ECS/Overview1.png',
        ],
      },
      {
        id: 84,
        name: 'AWS-ECS-CPU-Utilization-Cluster-And-Service',
        description: 'AWS ECS Operations',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ECS',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ECS/AWS ECS Metrics/AWS ECS - CPU Utilization - Cluster & Service.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ECS/CPU-Utilization-Cluster-And-Service.png',
        ],
      },
      {
        id: 85,
        name: 'AWS-ECS-CPU-&-MEMORY-RESERVATION-CLUSTER',
        description: 'AWS ECS Operations',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ECS',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ECS/AWS ECS Metrics/AWS ECS - CPU & Memory Reservation - Cluster.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ECS/CPU-and-Memory-Reservation-Cluster.png',
        ],
      },
      {
        id: 86,
        name: 'AWS-ECS-EVENTS',
        description: 'AWS ECS Events',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ECS',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ECS/AWS ECS Logs/Amazon ECS - Events.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ECS/Events.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ECS/Events1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ECS/Events2.png',
        ],
      },
      {
        id: 93,
        name: 'Amazon-ElastiCache-REDIS-ULM-EVENT-OVERVIEW',
        description: 'AWS ELASTICACHE Events Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ElastiCache',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ElastiCache Redis/Amazon-Elasticache-redis-ulm-events-overview.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ElastiCache/REDIS-ULM-Events-Overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ElastiCache/REDIS-ULM-Events-Overview1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ElastiCache/REDIS-ULM-Events-Overview2.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ElastiCache/REDIS-ULM-Events-Overview3.png',
        ],
      },
      {
        id: 97,
        name: 'Amazon-ElastiCache-Redis-ULM-Performance-Overview',
        description: 'AWS ElastiCache Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ElastiCache',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ElastiCache Redis/Amazon ElastiCache Redis ULM-Performance Overview.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ElastiCache/REDIS-ULM-PerformanceOverview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ElastiCache/REDIS-ULM-PerformanceOverview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ElastiCache/REDIS-ULM-PerformanceOverview2.png',
        ],
      },
      {
        id: 98,
        name: 'Amazon ElastiCache Redis ULM-Performance Overview',
        description: 'AWS ElastiCache Redis ULM Monitoring Performance Overview',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ElastiCache-Redis',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ElastiCache Redis/Amazon ElastiCache Redis ULM-Performance Overview.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ElastiCache/REDIS-ULM-PerformanceOverview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ElastiCache/REDIS-ULM-PerformanceOverview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ElastiCache/REDIS-ULM-PerformanceOverview2.png',
        ],
      },
      {
        id: 99,
        name: 'Amazon ElastiCache Redis ULM–Performance by Cluster',
        description: 'AWS ElastiCache Redis ULM Performance Monitoring by Cluster',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ElastiCache-Redis',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ElastiCache Redis/Amazon ElastiCache Redis ULM-Performance by Cluster.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ElastiCache/REDIS-ULM-performance-ByCluster.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ElastiCache/REDIS-ULM-performance-ByCluster1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ElastiCache/REDIS-ULM-performance-ByCluster2.png',
        ],
      },
      {
        id: 101,
        name: 'Amazon ElastiCache Redis ULM–Performance by Host',
        description: 'AWS ElastiCache Redis ULM Monitoring Performance by Host',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ElastiCache-Redis',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ElastiCache Redis/Amazon ElastiCache Redis ULM-Performance by Host.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ElastiCache/REDIS-ULM-PerformanceBy-host1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ElastiCache/REDIS-ULM-PerformanceBy-host2.png',
        ],
      },
      {
        id: 104,
        name: 'Amazon ElastiCache Redis ULM – Notifications',
        description: 'AWS ElastiCache Redis ULM Monitoring Notifications',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'ElastiCache-Redis',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon ElastiCache Redis/Amazon-elasticache-redis-ulm-notifications.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ElastiCache/ElastiCache-Redis-ULM–Notifications.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/ElastiCache/ElastiCache-Redis-ULM–Notifications1.png',
        ],
      },
      {
        id: 105,
        name: 'Amazon GuardDuty - Overview',
        description: 'Amazon GuardDuty Monitoring Performance Overview',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'GuardDuty',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon GuardDuty/Amazon GuardDuty-Overview.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/GuardDuty/GuardDuty-Overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/GuardDuty/GuardDuty-Overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/GuardDuty/GuardDuty-Overview2.png',
        ],
      },
      {
        id: 106,
        name: 'Amazon GuardDuty – CloudTrail Details',
        description: 'Amazon GuardDuty Monitoring CloudTrail Details',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'GuardDuty',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon GuardDuty/Amazon GuardDuty-CloudTrail-Details.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/GuardDuty/GuardDuty-CloudTrail Details1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/GuardDuty/GuardDuty-CloudTrail-Details.png',
        ],
      },
      {
        id: 108,
        name: 'Amazon GuardDuty - Details(VPC,Subnet,Security Group)',
        description: 'Amazon GuardDuty Monitoring VPC,Subnet,Security Group Details',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'GuardDuty',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon GuardDuty/Amazon GuardDuty-Details(VPC,SUBNETS.SG).json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/GuardDuty/GuardDuty-Details(VPC, SUBNETSecurity Group).png',
        ],
      },
      {
        id: 111,
        name: 'Amazon Kinesis – Streams - Events',
        description: 'Amazon Kinesis Streams Monitoring Events',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'AVAILABILITY',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Kinesis',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS kinesis/Amazon Kinesis - Streams - Events.json',
        images: ['https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/Kinesis/Kinesis-Streams-Events.png'],
      },
      {
        id: 118,
        name: 'Amazon Redshift - Overview',
        description: 'Amazon Redshift Monitoring Performance Overview ',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Redshift',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Redshift/AWS - RedShift Overview.json',
        images: ['https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/RedShift/Overview.png'],
      },
      {
        id: 119,
        name: 'Amazon Redshift - Overview',
        description: 'Amazon Redshift Monitoring Performance Overview ',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Redshift',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Redshift/AWS - RedShift Overview.json',
        images: ['https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/RedShift/Overview.png'],
      },
      {
        id: 120,
        name: 'Amazon Redshift – Audit - Connection Log',
        description: 'Amazon Redshift Monitoring and Audit connection Log',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Redshift',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Redshift/AWS - Redshift - Audit - Connection Log.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/RedShift/Audit-Connection-Log.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/RedShift/Audit-connection-Log1.png',
        ],
      },
      {
        id: 125,
        name: 'Amazon Redshift – CloudTrail Events Overview',
        description: 'Amazon Redshift Monitoring and Overview of CloudTrail Events',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Redshift',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Redshift/AWS - RedShift - CloudTrail events Overview1.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/RedShift/Cloudtrail-Events-Overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/RedShift/CloudTrail-Events-Overview1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/RedShift/Cloudtrail-Events-Overview2.png',
        ],
      },
      {
        id: 127,
        name: 'Amazon Redshift – Resource Utilization by ClusterIdentifier',
        description: 'Amazon Redshift Monitoring Resource Utilization by ClusterIdentifier ',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Redshift',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Redshift/AWS-Redshift-Resource utilization by cluster identifier.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/RedShift/Resource-Utilization-By-ClusterIdentifier.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/RedShift/Resource-Utilization-By-ClusterIdentifier1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/RedShift/Resource-Utilization-By-ClusterIdentifier2.png',
        ],
      },
      {
        id: 128,
        name: 'Amazon Redshift – Resource Utilization by NodeID',
        description: 'Amazon Redshift Monitoring Resource Utilization by NodeID ',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'Redshift',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS Redshift/AWS-Redshift-Resource utilization by NODE ID.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/RedShift/Resource-Utilization-By-NodeID.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/RedShift/Resource-Utilization-By-NodeID1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/RedShift/Resource-Utilization-By-NodeID2.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/RedShift/Resource-Utilization-By-NodeID3.png',
        ],
      },
      {
        id: 132,
        name: 'Amazon SES – CloudTrail Events Overview',
        description: 'Amazon SES Monitoring and Overview of CloudTrail Events',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SES',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon SES/Amazon SES - Cloud Trail Events Overview.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SES/cloudtrail-Events-overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SES/cloudtrail-Events-overview1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SES/cloudtrail-Events-overview2.png',
        ],
      },
      {
        id: 134,
        name: 'Amazon SES –CloudTrail Events by Event Name',
        description: 'Amazon SES Monitoring of CloudTrail Events by Event name',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SES',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon SES/AWS-SES-CLOUDTRAIL-EVENTS-BY-EVENTNAMES.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SES/CloudTrail Events by Eventname.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SES/CloudTrail Events by Eventname1.png',
        ],
      },
      {
        id: 141,
        name: 'Amazon SNS - Overview',
        description: 'Amazon SNS Performance Monitoring and OverView',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SNS',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS SNS/sns overview metrics.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SNS/Overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SNS/Overview1.png',
        ],
      },
      {
        id: 142,
        name: 'Amazon SNS - Overview',
        description: 'Amazon SNS Performance Monitoring and OverView',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SNS',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS SNS/sns overview logs.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SNS/Overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SNS/Overview1.png',
        ],
      },
      {
        id: 145,
        name: 'Amazon SNS – Metric by Region',
        description: 'Amazon SNS Region Monitoring by metrics',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SNS',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS SNS/Amazon SNS - Metric By Region.json',
        images: ['https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SNS/Metric-By-Region.png'],
      },
      {
        id: 146,
        name: 'Amazon SNS – Metric by TopicName',
        description: 'Amazon SNS TopicName Monitoring by metrics',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'USER END STATS',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SNS',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS SNS/Amazon SNS - Metric By TopicName.json',
        images: ['https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SNS/Metric-By-TopicName.png'],
      },
      {
        id: 147,
        name: 'Amazon SNS – CloudTrail Events',
        description: 'Amazon SNS Monitoring by CloudTrail Events',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'USER END STATS',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SNS',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS SNS/Amazon SNS - CloudTrail Events.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SNS/CloudTrail-Events.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SNS/CloudTrail-Events2.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SNS/CloudTrail-Events3.png',
        ],
      },
      {
        id: 149,
        name: 'Amazon SNS – CloudTrail Events',
        description: 'Amazon SQS Monitoring  by CloudTrail Events',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'USER END STATS',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SQS',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS-SQS/AWS-SQS-CloudTrail-Events.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SNS/CloudTrail-Events.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SNS/CloudTrail-Events2.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SNS/CloudTrail-Events3.png',
        ],
      },
      {
        id: 151,
        name: 'Amazon SQS – Overview',
        description: 'Amazon SQS Monitoring and Overview',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SQS',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS-SQS/sqs overview logs.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SQS/Amazon-SQS-Overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SQS/Amazon-SQS-Overview1.png',
        ],
      },
      {
        id: 152,
        name: 'Amazon SQS – Overview',
        description: 'Amazon SQS Monitoring and Overview',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SQS',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS-SQS/sqs overview metrics.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SQS/Amazon-SQS-Overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SQS/Amazon-SQS-Overview1.png',
        ],
      },
      {
        id: 153,
        name: 'Amazon SQS by QueueName',
        description: 'Amazon SQS Monitoring by QueueName',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'AVAILABILITY',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SQS',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS-SQS/AWS-SQS-QueueName.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SQS/Amazon-SQS-By-QueueName.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SQS/Amazon-SQS-By-QueueName1.png',
        ],
      },
      {
        id: 155,
        name: 'Amazon SQS by Region',
        description: 'Amazon SQS Monitoring by Region',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'AVAILABILITY',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'SQS',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS-SQS/AWS-SQS-By-Region.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SQS/Amazon-SQS-By-Region.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/SQS/Amazon-SQS-By-Region1.png',
        ],
      },
      {
        id: 157,
        name: 'Amazon VPC Flow Logs - Overview',
        description: 'Amazon VPC Flow Logs Monitoring and OverView',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'VPC',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/vpc/Amazon VPC Flow Logs - Overview.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/VPC/Flow-logs-overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/VPC/Flow-logs-overview1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/VPC/Flow-logs-overview1.png',
        ],
      },
      {
        id: 159,
        name: 'Amazon VPC Flow Logs - Traffic',
        description: 'Amazon VPC Flow Logs Monitoring Traffic',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'VPC',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/vpc/Amazon VPC Flow Logs - Traffic.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/VPC/flowLogs-Traffic.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/VPC/flowLogs-Traffic1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/VPC/flowLogs-Traffic2.png',
        ],
      },
      {
        id: 161,
        name: 'Amazon VPC Flow Logs - Accepts',
        description: 'Amazon VPC Flow Logs Monitoring by Accepts',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'VPC',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/vpc/Amazon VPC Flow Logs - Accepts.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/VPC/Accepted-flowLogs.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/VPC/Accepted-flowLogs1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/VPC/Accepted-flowLogs2.png',
        ],
      },
      {
        id: 163,
        name: 'Amazon VPC Flow Logs - Rejects',
        description: 'Amazon VPC Flow Logs Monitoring by Rejects',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'VPC',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/vpc/Amazon VPC Flow Logs - Rejects.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/VPC/FlowLogs-Rejects.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/VPC/FlowLogs-Rejects1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/VPC/FlowLogs-Rejects2.png',
        ],
      },
      {
        id: 167,
        name: 'CIS AWS Monitoring – Access & Authentication',
        description: 'CIS AWS Monitoring Access & Authentication',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'USER END STATS',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CIS',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/CIS AWS Monitoring- Access & Authentication/CIS AWS Monitoring – Access & Authentication.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/CIS/Monitoring-Access-and-Authentication.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/CIS/Monitoring-Access-and-Authentication1.png',
        ],
      },
      {
        id: 168,
        name: 'CIS AWS Monitoring – Change Control',
        description: 'CIS AWS Monitoring Change Control',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'USER END STATS',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CIS',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/CIS AWS Monitoring- Access & Authentication/CIS AWS Monitoring - Change Control.json',
        images: ['https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/CIS/Monitoring -Control-Change.png'],
      },
      {
        id: 169,
        name: 'GI GuardDuty – Global Baseline',
        description: 'GI GuardDuty Monitoring Global Baseline',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'GI-GuardDuty',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon GI GuardDuty/GI GuardDuty Global Baseline.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/GI/GuardDuty-GlobalBaseline.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/GI/GuardDuty-GlobalBaseline1.png',
        ],
      },
      {
        id: 173,
        name: 'GI GuardDuty – Findings Analysis',
        description: 'GI GuardDuty Monitoring and Findings Analysis',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'GI-GuardDuty',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon GI GuardDuty/GI GuardDuty Finding Analysis.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/GI/GuardDuty-Finding-Analysis.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/GI/GuardDuty-Finding-Analysis1.png',
        ],
      },
      {
        id: 174,
        name: 'GI GuardDuty – Findings Analysis(1)',
        description: 'GI GuardDuty Monitoring and Findings Analysis',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'GI-GuardDuty',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon GI GuardDuty/GI GuardDuty Finding Analysis(1).json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/GI/GuardDuty-Finding-Analysis.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/GI/GuardDuty-Finding-Analysis1.png',
        ],
      },
      {
        id: 180,
        name: 'GI CloudTrail – Tactics & Techniques',
        description: 'GI CloudTrail Monitoring Tactics & Techniques',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'GI-CloudTrail',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon GI CloudTrail/GI CloudTrail Tactic and Techniques.json',
        images: ['https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/GI/CloudTrail-Tactics-and-Techniques.png'],
      },
      {
        id: 184,
        name: 'GI CloudTrail – Action Plan',
        description: 'GI CloudTrail Monitoring by Action Plan',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'USER END STATS',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'GI-CloudTrail',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon GI CloudTrail/GI CloudTrail Action Plan.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/GI/CloudTrail-ActionPlan1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/GI/CloudTrail-ActionPlan2.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/GI/CloudTrail-ActionPlan3.png',
        ],
      },
      {
        id: 185,
        name: 'GI CloudTrail – Action Plan(1)',
        description: 'GI CloudTrail Monitoring by Action Plan',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'USER END STATS',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'GI-CloudTrail',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/Amazon GI CloudTrail/GI CloudTrail Action Plan(1).json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/GI/CloudTrail-ActionPlan1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/GI/CloudTrail-ActionPlan2.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/GI/CloudTrail-ActionPlan3.png',
        ],
      },
      {
        id: 187,
        name: 'AWS CloudTrail - Access Monitoring',
        description: 'CloudTrail - Access Monitoring Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'USER END STATS',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CloudTrail',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/CloudTrail/AWS-CloudTrails-logs/AWS CloudTrail - Access Monitoring.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/CloudTrail/Amazon-CloudTrail-Access-Monitoring1.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/CloudTrail/Amazon-CloudTrail-Access-Monitoring2.png',
        ],
      },
      {
        id: 188,
        name: 'AWS CloudTrail - Account, System Monitoring',
        description: 'CloudTrail - Account & System Monitoring Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'USER END STATS',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CloudTrail',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/CloudTrail/AWS-CloudTrails-logs/AWS CloudTrail - Account , System Monitoring.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/CloudTrail/Amazon-CloudTrail-Account-System-Monitoring.png',
        ],
      },
      {
        id: 189,
        name: 'AWS CloudTrail -Privileged Activity',
        description: 'CloudTrail -Privileged Activity Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'USER END STATS',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CloudTrail',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/CloudTrail/AWS-CloudTrails-logs/AWS CloudTrail -Privileged Activity.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/CloudTrail/Amazon-CloudTrail-Account-Privileged Activity.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/CloudTrail/Amazon-CloudTrail-Account-Privileged-Activity1.png',
        ],
      },
      {
        id: 190,
        name: 'AWS CloudTrail -Login Activity',
        description: 'CloudTrail -Login Activity Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'USER END STATS',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'CloudTrail',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/AWS Dashboards/CloudTrail/AWS-CloudTrails-logs/AWS CloudTrail -Login Activity.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/CloudTrail/Amazon-CloudTrail-Login-Activity.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/CloudTrail/Amazon-CloudTrail-Login-Activity1.png',
        ],
      },
      {
        id: 195,
        name: 'AWS WAF - Overview',
        description: 'WAF Monitering Overview',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'WAF',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS WAF/waf overview logs.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/WAF/Overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/WAF/Overview1.png',
        ],
      },
      {
        id: 196,
        name: 'AWS WAF - Overview',
        description: 'WAF Monitering Overview',
        associatedDataSourceType: 'AWS-PullMetric-Api',
        associatedDataType: 'METRIC',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'WAF',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS WAF/waf overview metrics.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/WAF/Overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/WAF/Overview1.png',
        ],
      },
      {
        id: 197,
        name: 'AWS WAF - Security Analytics Traffic',
        description: 'WAF - Security Analytics Traffic Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'WAF',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS WAF/waf-security-analysis-traffic.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/WAF/Security-Analysis-Traffic.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/WAF/Security-Analysis-Traffic1.png',
        ],
      },
      {
        id: 199,
        name: 'AWS WAF - Security Monitoring Overview',
        description: 'WAF - Security Monitoring Overview Operations',
        associatedDataSourceType: 'AWS-PullLog-Api',
        associatedDataType: 'LOG',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'AWS',
        associatedCloudElementType: 'WAF',
        jsonLocation: 's3://synectiks-monitoring-dashboards/AWS Dashboards/AWS WAF/waf-security-monitoring.json',
        images: [
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/WAF/Security-Monitoring-Overview.png',
          'https://syn-monitoring-images.s3.amazonaws.com/AWS-Images/WAF/Security-Monitoring-Overview1.png',
        ],
      },
      {
        id: 1,
        name: 'Azure Active Directory - Overview',
        description: 'Azure Active Directory Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Active Directory-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Active Directory/Azure Active Directory - Overview.json',
      },
      {
        id: 2,
        name: 'Azure Active Directory - Application Management',
        description: 'Azure Active Directory Applicaion Management Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Active Directory-Application Management Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Active Directory/Azure Active Directory - Application Management.json',
      },
      {
        id: 3,
        name: 'Azure Active Directory -  Authorization/Authentication',
        description: 'Azure Active Directory Applicaion Management Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Active Directory-Application Management Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Active Directory/Azure Active Directory - Authorization, Authentication.json',
      },
      {
        id: 4,
        name: 'Azure Active Directiory - Directory Management',
        description: 'Azure Active Directory management Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Active Directory Management Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Active Directory/Azure Active Directory - Directory Management.json',
      },
      {
        id: 5,
        name: 'Azure Active Directory - Failure Sign-in Events ',
        description: 'Azure Active Directory Failed Sign-in Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Active Directory Failed Sign-in Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Active Directory/Azure Active Directory -- Failure Sign_In Events.json',
      },
      {
        id: 6,
        name: 'Azure Active Directory - Successful  Sign-in Events ',
        description: 'Azure Active Directory Success Sign-in Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Active Directory Success Sign-in Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Active Directory/Azure Active Directory - Success Sign-Ins.json',
      },
      {
        id: 7,
        name: 'Azure Audit - Overview',
        description: 'Azure Audit - Overview- Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Azure Audit - Overview',
        jsonLocation: 's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Audit/Azure Audit - OverView.json',
      },
      {
        id: 8,
        name: 'Azure Audit Resource usage',
        description: 'Azure Audit Resource usage - Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Azure Audit - Resource Usasge',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Audit/Azure Audit - Resource Usage.json',
      },
      {
        id: 9,
        name: 'Azure SQL – Blocking Stats',
        description: ' SQL – Blocking Stats - Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Azure SQL – Blocking Stats',
        jsonLocation: 's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure SQL/Azure SQL-Blocking Stats.json',
      },
      {
        id: 10,
        name: 'Azure SQL –Errors',
        description: ' SQL – Errors - Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Azure SQL – Errors',
        jsonLocation: 's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure SQL/Azure SQL Errors.json',
      },
      {
        id: 11,
        name: 'Azure SQL – QueryStoreRuntime Stats',
        description: 'SQL – QueryStoreRuntime Stats  Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Azure SQL – QueryStoreRuntime Stats',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure SQL/Azure SQL - Query StoreRuntime Stats.json',
      },
      {
        id: 12,
        name: 'Azure SQL – QueryStoreWait Stats',
        description: 'Azure SQL – QueryStoreWait Stats  Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Azure SQL – QueryStoreRuntime',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure SQL/Azure SQL-Query Store Wait Stats.json',
      },
      {
        id: 13,
        name: 'Azure SQL – Timeouts',
        description: 'Azure SQL – Timeouts  Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Azure SQL – Timeouts',
        jsonLocation: 's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure SQL/Azure SQL TimeOuts.json',
      },
      {
        id: 14,
        name: 'Azure Web Apps Overview',
        description: 'Azure Web Apps – Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Azure Web Apps',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Web Apps/Azure Web Apps-Overview.json',
      },
      {
        id: 15,
        name: 'Azure Web Apps – Server Operation – Errors and Response Codes',
        description: 'Azure Web Server Operation – Errors and Response Codes',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Azure Web Apps',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Web Apps/Azure Web Apps-Server Operation-Errors and Response Codes.json',
      },
      {
        id: 16,
        name: 'Azure Web Apps – Traffic Insights – Apps and Requests',
        description: 'Azure Web Apps – Traffic Insights – Apps and Requests',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Azure Web Apps',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Web Apps/Azure Web Apps - Traffic insights - Apps and requests.json',
      },
      {
        id: 17,
        name: 'Office 365 – SharePoint – Shared Content Non-Domain Activities',
        description: 'Office 365 – SharePoint – Shared Content Non-Domain Activities Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Office 365',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Office 365/Office 365 – SharePoint – Shared Content Non – Domain Activities.json',
      },
    ],
    dataSources: [
      {
        id: 1,
        name: 'AWS-PullMetric-Api',
        description: 'Pull AWS metrics with Cloud API',
        Type: 'PullApi',
        DataType: 'METRIC',
        associatedWorkflowTemplate: 's3://...',
        associatedCloud: 'AWS',
        associatedCreds: 'Vault',
        associatedApplicationLocation: 'AppKubeMain',
        associatedTargetDs: 'NA',
      },
      {
        id: 2,
        name: 'AWS-PullLogs-Api',
        description: 'Pull AWS Logs with Cloud API',
        Type: 'PullApi',
        DataType: 'LOG',
        associatedWorkflowTemplate: 's3://...',
        associatedCloud: 'AWS',
        associatedCreds: 'Vault',
        associatedApplicationLocation: 'AppKubeMain',
        associatedTargetDs: 'NA',
      },
      {
        id: 3,
        name: 'AWS-PullLogs-Local',
        description: 'Receive AWS Logs and Store in Local ES',
        Type: 'ReceiveAndStoreLogs',
        DataType: 'LOG',
        associatedWorkflowTemplate: 's3://...',
        associatedCloud: 'AWS',
        associatedCreds: 'Vault',
        associatedApplicationLocation: 'LogManager',
        associatedTargetDsType: 'ES',
      },
      {
        id: 4,
        name: 'AWS-StoreTrace-Local',
        description: 'Receive Traces and Store in Local Zipkin DB',
        Type: 'ReceiveAndStoreTrace',
        DataType: 'Trace',
        associatedWorkflowTemplate: 's3://...',
        associatedCloud: 'AWS',
        associatedCreds: 'Vault',
        associatedApplicationLocation: 'TraceManager',
        associatedTargetDsType: 'Zipkin',
      },
      {
        id: 4,
        name: 'Azure-PullMetric-Api',
        description: 'Pull Azure metrics with Cloud API',
        Type: 'PullApi',
        DataType: 'METRIC',
        associatedWorkflowTemplate: 's3://...',
        associatedCloud: 'Azure',
        associatedCreds: 'Vault',
        associatedApplicationLocation: 'AppKubeMain',
        associatedTargetDs: 'NA',
      },
      {
        id: 5,
        name: 'Azure-PullLogs-Api',
        description: 'Pull Azure Logs with Cloud API',
        Type: 'PullApi',
        DataType: 'LOG',
        associatedWorkflowTemplate: 's3://...',
        associatedCloud: 'Azure',
        associatedCreds: 'Vault',
        associatedApplicationLocation: 'AppKubeMain',
        associatedTargetDs: 'NA',
      },
      {
        id: 6,
        name: 'Azure-PullLogs-Local',
        description: 'Receive Azure Logs and Store in Local ES',
        Type: 'ReceiveAndStoreLogs',
        DataType: 'LOG',
        associatedWorkflowTemplate: 's3://...',
        associatedCloud: 'Azure',
        associatedCreds: 'Vault',
        associatedApplicationLocation: 'LogManager',
        associatedTargetDsType: 'ES',
      },
      {
        id: 7,
        name: 'Azure-StoreTrace-Local',
        description: 'Receive Traces and Store in Local Zipkin DB',
        Type: 'ReceiveAndStoreTrace',
        DataType: 'Trace',
        associatedWorkflowTemplate: 's3://...',
        associatedCloud: 'AWS',
        associatedCreds: 'Vault',
        associatedApplicationLocation: 'TraceManager',
        associatedTargetDsType: 'Zipkin',
      },
      {
        id: 8,
        name: 'Azure Active Directory - Overview',
        description: 'Azure Active Directory Operations',
        associatedDataSourceType: 'Azure-PullLog-Api',
        associatedDataType: 'Log',
        associatedSLAType: 'PERFORMANCE',
        associatedCloud: 'Azure',
        associatedCloudElementType: 'Active Directory-Operations',
        jsonLocation:
          's3://synectiks-monitoring-dashboards/Azure Dashboards/Azure Active Directory/Azure Active Directory - Overview.json',
      },
    ],
    provisioningTemplates: [
      {
        id: 1,
        name: 'AWS-Landing-Zone',
        description: 'Create AWS Accounts with Best Practices',
        Type: 'LandingZone',
        actOn: 'MainProduct',
        associatedSpecsTemplate: 's3://...',
        associatedCloud: 'AWS',
        associatedCreds: 'Vault',
      },
      {
        id: 2,
        name: 'Azure-Landing-Zone',
        description: 'Create Azure Account and Subscription with Best Practices',
        Type: 'LandingZone',
        actOn: 'MainProduct',
        associatedSpecsTemplate: 's3://...',
        associatedCloud: 'Azure',
        associatedCreds: 'Vault',
      },
      {
        id: 3,
        name: 'Google-Landing-Zone',
        description: 'Create Google Project with Best Practices',
        Type: 'LandingZone',
        actOn: 'MainProduct',
        associatedSpecsTemplate: 's3://...',
        associatedCloud: 'Google',
        associatedCreds: 'Vault',
      },
      {
        id: 4,
        name: 'AWS-Product-Enclave',
        description: 'Create AWS VPC/Gateway/Firewall Services',
        Type: 'ProductEnclave',
        actOn: 'LandingZone',
        associatedSpecsTemplate: 's3://...',
        associatedCloud: 'AWS',
        associatedCreds: 'Vault',
      },
      {
        id: 5,
        name: 'Azure-Product-Enclave',
        description: 'Create Azure VPC/Gateway/Firewall Services',
        Type: 'ProductEnclave',
        actOn: 'LandingZone',
        associatedSpecsTemplate: 's3://...',
        associatedCloud: 'Azure',
        associatedCreds: 'Vault',
      },
      {
        id: 6,
        name: 'Google-Product-Enclave',
        description: 'Create Google VPC/Gateway/Firewall Services',
        Type: 'ProductEnclave',
        actOn: 'LandingZone',
        associatedSpecsTemplate: 's3://...',
        associatedCloud: 'Google',
        associatedCreds: 'Vault',
      },
      {
        id: 7,
        name: 'AWS-Product-Cluster',
        description: 'Create EKS k8 cluster with best practices',
        Type: 'ProductCluster',
        actOn: 'ProductEnclave',
        associatedSpecsTemplate: 's3://...',
        associatedCloud: 'AWS',
        associatedCreds: 'Vault',
      },
      {
        id: 8,
        name: 'Azure-Product-Cluster',
        description: 'Create Azure AKS k8 cluster with best practices',
        Type: 'ProductCluster',
        actOn: 'ProductEnclave',
        associatedSpecsTemplate: 's3://...',
        associatedCloud: 'Azure',
        associatedCreds: 'Vault',
      },
      {
        id: 9,
        name: 'Google-Product-Cluster',
        description: 'Create Google k8 cluster with best practices',
        Type: 'ProductCluster',
        actOn: 'ProductEnclave',
        associatedSpecsTemplate: 's3://...',
        associatedCloud: 'Google',
        associatedCreds: 'Vault',
      },
      {
        id: 10,
        name: 'Common-Service-File-Repo',
        description: 'Provision Filerepo Common Services',
        Type: 'CommonService',
        actOn: 'ProductEnclave',
        associatedSpecsTemplate: 's3://...',
        associatedCloud: 'Google',
        associatedCreds: 'Vault',
      },
    ],
    alertRules: {},
    workflows: {
      name: null,
    },
    collectors: {
      name: null,
    },
    diagonostics: {
      name: null,
    },
    kubeOperators: {
      name: null,
    },
  },
};
