export default [
  {
    title: 'VPC 1',
    unit: '',
    instance: 'N/A',
    status: true,
    isOpened: false,
    subData: [
      {
        title: 'Cluster 1',
        unit: '',
        instance: 'N/A',
        status: true,
        isOpened: false,
        subData: [
          {
            title: 'App Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            serviceSubData: [
              {
                title: 'Common Services',
                unit: '',
                instance: 'N/A',
                status: true,
                isOpened: false,
                list: [
                  {
                    title: 'Search',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Security/RBAC',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Preference/Config',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'DataFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Catalogue',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'WorkFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Alert',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Atate Machine',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                ],
              },
              {
                title: 'Business Services',
                unit: '',
                instance: 'N/A',
                status: true,
                serviceSubData: [
                  {
                    title: 'EMS',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Supply chain',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Procurment',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            title: 'Data Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            list: [
              { title: 'Search', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Security/RBAC',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              {
                title: 'Preference/Config',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'DataFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Catalogue',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'WorkFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              { title: 'Alert', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Atate Machine',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
            ],
          },
        ],
      },
      {
        title: 'Cluster 2',
        unit: '',
        instance: 'N/A',
        status: true,
        isOpened: false,
        subData: [
          {
            title: 'App Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            serviceSubData: [
              {
                title: 'Common Services',
                unit: '',
                instance: 'N/A',
                status: true,
                list: [
                  {
                    title: 'Search',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Security/RBAC',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Preference/Config',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'DataFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Catalogue',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'WorkFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Alert',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Atate Machine',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                ],
              },
              {
                title: 'Business Services',
                unit: '',
                instance: 'N/A',
                status: true,
                subData: [
                  {
                    title: 'EMS',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Supply chain',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Procurment',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            title: 'Data Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            list: [
              { title: 'Search', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Security/RBAC',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              {
                title: 'Preference/Config',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'DataFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Catalogue',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'WorkFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              { title: 'Alert', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Atate Machine',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
            ],
          },
        ],
      },
      {
        title: 'Cloud Manager Services',
        unit: '',
        instance: 'N/A',
        status: true,
        isOpened: false,
        subData: [
          {
            title: 'App Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            list: [
              { title: 'Search', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Security/RBAC',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              {
                title: 'Preference/Config',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'DataFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Catalogue',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'WorkFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              { title: 'Alert', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Atate Machine',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
            ],
          },
          {
            title: 'Data Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            serviceSubData: [
              {
                title: 'Common Services',
                unit: '',
                instance: 'N/A',
                status: true,
                isOpened: false,
                list: [
                  {
                    title: 'Search',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Security/RBAC',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Preference/Config',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'DataFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Catalogue',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'WorkFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Alert',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Atate Machine',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                ],
              },
              {
                title: 'Business Services',
                unit: '',
                instance: 'N/A',
                status: true,
                isOpened: false,
                serviceSubData: [
                  {
                    title: 'EMS',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Supply chain',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Procurment',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    title: 'VPC 2',
    unit: '',
    instance: 'N/A',
    status: true,
    isOpened: false,
    subData: [
      {
        title: 'Cluster 1',
        unit: '',
        instance: 'N/A',
        status: true,
        isOpened: false,
        subData: [
          {
            title: 'App Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            serviceSubData: [
              {
                title: 'Common Services',
                unit: '',
                instance: 'N/A',
                status: true,
                isOpened: false,
                list: [
                  {
                    title: 'Search',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Security/RBAC',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Preference/Config',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'DataFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Catalogue',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'WorkFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Alert',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Atate Machine',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                ],
              },
              {
                title: 'Business Services',
                unit: '',
                instance: 'N/A',
                status: true,
                serviceSubData: [
                  {
                    title: 'EMS',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Supply chain',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Procurment',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            title: 'Data Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            list: [
              { title: 'Search', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Security/RBAC',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              {
                title: 'Preference/Config',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'DataFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Catalogue',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'WorkFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              { title: 'Alert', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Atate Machine',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
            ],
          },
        ],
      },
      {
        title: 'Cluster 2',
        unit: '',
        instance: 'N/A',
        status: true,
        isOpened: false,
        subData: [
          {
            title: 'App Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            serviceSubData: [
              {
                title: 'Common Services',
                unit: '',
                instance: 'N/A',
                status: true,
                list: [
                  {
                    title: 'Search',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Security/RBAC',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Preference/Config',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'DataFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Catalogue',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'WorkFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Alert',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Atate Machine',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                ],
              },
              {
                title: 'Business Services',
                unit: '',
                instance: 'N/A',
                status: true,
                subData: [
                  {
                    title: 'EMS',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Supply chain',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Procurment',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            title: 'Data Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            list: [
              { title: 'Search', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Security/RBAC',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              {
                title: 'Preference/Config',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'DataFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Catalogue',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'WorkFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              { title: 'Alert', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Atate Machine',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
            ],
          },
        ],
      },
      {
        title: 'Cloud Manager Services',
        unit: '',
        instance: 'N/A',
        status: true,
        isOpened: false,
        subData: [
          {
            title: 'App Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            list: [
              { title: 'Search', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Security/RBAC',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              {
                title: 'Preference/Config',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'DataFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Catalogue',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'WorkFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              { title: 'Alert', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Atate Machine',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
            ],
          },
          {
            title: 'Data Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            serviceSubData: [
              {
                title: 'Common Services',
                unit: '',
                instance: 'N/A',
                status: true,
                isOpened: false,
                list: [
                  {
                    title: 'Search',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Security/RBAC',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Preference/Config',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'DataFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Catalogue',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'WorkFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Alert',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Atate Machine',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                ],
              },
              {
                title: 'Business Services',
                unit: '',
                instance: 'N/A',
                status: true,
                isOpened: false,
                serviceSubData: [
                  {
                    title: 'EMS',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Supply chain',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Procurment',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];

// if (subFolder.subData && subFolder.subData.length > 0) {
//   for (let k = 0; k < subFolder.subData.length; k++) {
//     if (subFolder.subData[k].isOpened == true) {
//       subRightFolderJSX.push(
//         <div className="data-table">
//           <div className="thead">
//             <div className="name">
//               Name
//             </div>
//             <div className="performance">
//               Performance
//             </div>
//             <div className="availability">
//               Availability
//             </div>
//             <div className="security">
//               Security
//             </div>
//             <div className="data-protection">
//               Data Protection
//             </div>
//             <div className="user-exp">
//               User exp
//             </div>
//           </div>
//           <div className="tbody">
//             <div className="name">
//               Common Services <span> <i className="fa fa-angle-down"></i></span>
//             </div>
//           </div>
//           <div className="inner-table">
//             <div className="tbody">
//               <div className="name">Search</div>
//               <div className="performance"><div className="status green"><i className="fa fa-check"></i></div></div>
//               <div className="availability"><div className="status yellow"><i className="fa fa-check"></i></div></div>
//               <div className="security"><div className="status orange"><i className="fa fa-check"></i></div></div>
//               <div className="data-protection"><div className="status red"><i className="fa fa-check"></i></div></div>
//               <div className="user-exp"><div className="status green"><i className="fa fa-check"></i></div></div>
//             </div>
//             <div className="tbody">
//               <div className="name">Security / RBAC</div>
//               <div className="performance"><div className="status yellow"><i className="fa fa-check"></i></div></div>
//               <div className="availability"><div className="status red"><i className="fa fa-check"></i></div></div>
//               <div className="security"><div className="status orange"><i className="fa fa-check"></i></div></div>
//               <div className="data-protection"><div className="status red"><i className="fa fa-check"></i></div></div>
//               <div className="user-exp"><div className="status green"><i className="fa fa-check"></i></div></div>
//             </div>
//             <div className="tbody">
//               <div className="name">Preference/Config</div>
//               <div className="performance"><div className="status red"><i className="fa fa-check"></i></div></div>
//               <div className="availability"><div className="status green"><i className="fa fa-check"></i></div></div>
//               <div className="security"><div className="status orange"><i className="fa fa-check"></i></div></div>
//               <div className="data-protection"><div className="status yellow"><i className="fa fa-check"></i></div></div>
//               <div className="user-exp"><div className="status green"><i className="fa fa-check"></i></div></div>
//             </div>
//             <div className="tbody">
//               <div className="name">DataFlow / Nifi</div>
//               <div className="performance"><div className="status orange"><i className="fa fa-check"></i></div></div>
//               <div className="availability"><div className="status red"><i className="fa fa-check"></i></div></div>
//               <div className="security"><div className="status orange"><i className="fa fa-check"></i></div></div>
//               <div className="data-protection"><div className="status yellow"><i className="fa fa-check"></i></div></div>
//               <div className="user-exp"><div className="status green"><i className="fa fa-check"></i></div></div>
//             </div>
//           </div>
//           <div className="tbody">
//             <div className="name">
//               Common Services <span> <i className="fa fa-angle-down"></i></span>
//             </div>
//           </div>
//         </div>
//       )
//     }
//   }
// }
