export default [
  {
    title: 'VPC 1',
    unit: '',
    instance: 'N/A',
    status: true,
    isOpened: false,
    subData: [
      {
        title: 'Cluster 1',
        unit: '',
        instance: 'N/A',
        status: true,
        isOpened: false,
        subData: [
          {
            title: 'App Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            serviceSubData: [
              {
                title: 'Common Services',
                unit: '',
                instance: 'N/A',
                status: true,
                isOpened: false,
                list: [
                  {
                    title: 'Search',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Security/RBAC',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Preference/Config',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'DataFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Catalogue',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'WorkFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Alert',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Atate Machine',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                ],
              },
              {
                title: 'Business Services',
                unit: '',
                instance: 'N/A',
                status: true,
                isOpened: false,
                serviceSubData: [
                  {
                    title: 'EMS',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    isOpened: false,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Supply chain',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    isOpened: false,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Procurment',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    isOpened: false,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            title: 'Data Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            list: [
              { title: 'Search', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Security/RBAC',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              {
                title: 'Preference/Config',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'DataFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Catalogue',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'WorkFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              { title: 'Alert', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Atate Machine',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
            ],
          },
        ],
      },
      {
        title: 'Cluster 2',
        unit: '',
        instance: 'N/A',
        status: true,
        isOpened: false,
        subData: [
          {
            title: 'App Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            serviceSubData: [
              {
                title: 'Common Services',
                unit: '',
                instance: 'N/A',
                status: true,
                isOpened: false,
                list: [
                  {
                    title: 'Search',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Security/RBAC',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Preference/Config',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'DataFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Catalogue',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'WorkFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Alert',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Atate Machine',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                ],
              },
              {
                title: 'Business Services',
                unit: '',
                instance: 'N/A',
                status: true,
                isOpened: false,
                subData: [
                  {
                    title: 'EMS',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    isOpened: false,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Supply chain',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    isOpened: false,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Procurment',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    isOpened: false,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            title: 'Data Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            list: [
              { title: 'Search', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Security/RBAC',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              {
                title: 'Preference/Config',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'DataFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Catalogue',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'WorkFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              { title: 'Alert', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Atate Machine',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
            ],
          },
        ],
      },
      {
        title: 'Cloud Manager Services',
        unit: '',
        instance: 'N/A',
        status: true,
        isOpened: false,
        subData: [
          {
            title: 'App Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            list: [
              { title: 'Search', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Security/RBAC',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              {
                title: 'Preference/Config',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'DataFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Catalogue',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'WorkFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              { title: 'Alert', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Atate Machine',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
            ],
          },
          {
            title: 'Data Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            serviceSubData: [
              {
                title: 'Common Services',
                unit: '',
                instance: 'N/A',
                status: true,
                isOpened: false,
                list: [
                  {
                    title: 'Search',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Security/RBAC',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Preference/Config',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'DataFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Catalogue',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'WorkFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Alert',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Atate Machine',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                ],
              },
              {
                title: 'Business Services',
                unit: '',
                instance: 'N/A',
                status: true,
                isOpened: false,
                serviceSubData: [
                  {
                    title: 'EMS',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    isOpened: false,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Supply chain',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    isOpened: false,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Procurment',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    isOpened: false,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
    isMain: true,
  },
  {
    title: 'VPC 2',
    unit: '',
    instance: 'N/A',
    status: true,
    isOpened: false,
    subData: [
      {
        title: 'Cluster 1',
        unit: '',
        instance: 'N/A',
        status: true,
        isOpened: false,
        subData: [
          {
            title: 'App Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            serviceSubData: [
              {
                title: 'Common Services',
                unit: '',
                instance: 'N/A',
                status: true,
                isOpened: false,
                list: [
                  {
                    title: 'Search',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Security/RBAC',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Preference/Config',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'DataFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Catalogue',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'WorkFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Alert',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Atate Machine',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                ],
              },
              {
                title: 'Business Services',
                unit: '',
                instance: 'N/A',
                status: true,
                isOpened: false,
                serviceSubData: [
                  {
                    title: 'EMS',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    isOpened: false,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Supply chain',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    isOpened: false,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Procurment',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    isOpened: false,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            title: 'Data Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            list: [
              { title: 'Search', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Security/RBAC',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              {
                title: 'Preference/Config',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'DataFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Catalogue',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'WorkFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              { title: 'Alert', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Atate Machine',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
            ],
          },
        ],
      },
      {
        title: 'Cluster 2',
        unit: '',
        instance: 'N/A',
        status: true,
        isOpened: false,
        subData: [
          {
            title: 'App Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            serviceSubData: [
              {
                title: 'Common Services',
                unit: '',
                instance: 'N/A',
                status: true,
                isOpened: false,
                list: [
                  {
                    title: 'Search',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Security/RBAC',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Preference/Config',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'DataFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Catalogue',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'WorkFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Alert',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Atate Machine',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                ],
              },
              {
                title: 'Business Services',
                unit: '',
                instance: 'N/A',
                status: true,
                isOpened: false,
                subData: [
                  {
                    title: 'EMS',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    isOpened: false,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Supply chain',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    isOpened: false,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Procurment',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    isOpened: false,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            title: 'Data Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            list: [
              { title: 'Search', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Security/RBAC',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              {
                title: 'Preference/Config',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'DataFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Catalogue',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'WorkFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              { title: 'Alert', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Atate Machine',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
            ],
          },
        ],
      },
      {
        title: 'Cloud Manager Services',
        unit: '',
        instance: 'N/A',
        status: true,
        isOpened: false,
        subData: [
          {
            title: 'App Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            list: [
              { title: 'Search', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Security/RBAC',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              {
                title: 'Preference/Config',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'DataFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Catalogue',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
              { title: 'WorkFlow', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              { title: 'Alert', performance: 80, availibility: 80, security: 80, data_protection: 90, user_exp: 85 },
              {
                title: 'Atate Machine',
                performance: 80,
                availibility: 80,
                security: 80,
                data_protection: 90,
                user_exp: 85,
              },
            ],
          },
          {
            title: 'Data Services',
            unit: '',
            instance: 'N/A',
            status: true,
            isOpened: false,
            serviceSubData: [
              {
                title: 'Common Services',
                unit: '',
                instance: 'N/A',
                status: true,
                isOpened: false,
                list: [
                  {
                    title: 'Search',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Security/RBAC',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Preference/Config',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'DataFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Catalogue',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'WorkFlow',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Alert',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                  {
                    title: 'Atate Machine',
                    performance: 80,
                    availibility: 80,
                    security: 80,
                    data_protection: 90,
                    user_exp: 85,
                  },
                ],
              },
              {
                title: 'Business Services',
                unit: '',
                instance: 'N/A',
                status: true,
                isOpened: false,
                serviceSubData: [
                  {
                    title: 'EMS',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    isOpened: false,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Supply chain',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    isOpened: false,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                  {
                    title: 'Procurment',
                    unit: '',
                    instance: 'N/A',
                    status: true,
                    isOpened: false,
                    list: [
                      {
                        title: 'Search',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Security/RBAC',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Preference/Config',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'DataFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Catalogue',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'WorkFlow',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Alert',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                      {
                        title: 'Atate Machine',
                        performance: 80,
                        availibility: 80,
                        security: 80,
                        data_protection: 90,
                        user_exp: 85,
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
    isMain: true,
  },
];
